(function (root) {
  'use strict';
  // แหล่งข้อมูลแต่ละรายการเป็นหน้าเจ้าของหลักสูตรหรือเจ้าของสถานที่ ตรวจ 25 ก.ย. 2569
  const universities = [
    { name:'มหาวิทยาลัยมหิดล', faculty:'วิทยาลัยดุริยางคศิลป์', province:'นครปฐม', region:'central', levels:'ปริญญาตรี', majors:['ดนตรีคลาสสิก','แจ๊ส','ดนตรีสมัยนิยม','ละครเพลง','ดนตรีไทยและตะวันออก','ประพันธ์เพลง','ธุรกิจดนตรี','ดนตรีศึกษาและการสอน','เทคโนโลยีดนตรี'], url:'https://openhouse.mahidol.ac.th/faculties/ms/ms-1/', extra:'https://www.music.mahidol.ac.th/academic/bachelor/', note:'วิทยาเขตศาลายา อยู่นอกกรุงเทพฯ' },
    { name:'มหาวิทยาลัยศิลปากร', faculty:'คณะดุริยางคศาสตร์', province:'กรุงเทพมหานคร', region:'bangkok', levels:'ปริญญาตรี–เอก', majors:['ดนตรีคลาสสิก','ดนตรีและสื่อสร้างสรรค์','แจ๊ส','ดนตรีเชิงพาณิชย์','ละครเพลง','ผู้ประกอบการดนตรีศึกษา','ธุรกิจดนตรีและบันเทิง','การจัดการไอดอลและอินฟลูเอนเซอร์'], url:'https://music.su.ac.th/programs/', note:'ปริญญาตรีมีทั้ง ดศ.บ. และ ศศ.บ.; รายการแสดงวิชาเอกของทั้งสองหลักสูตร' },
    { name:'จุฬาลงกรณ์มหาวิทยาลัย', faculty:'คณะศิลปกรรมศาสตร์ · ภาควิชาดุริยางคศิลป์', province:'กรุงเทพมหานคร', region:'bangkok', levels:'ปริญญาตรี', majors:['ดนตรีไทย','ดนตรีสากล'], url:'https://www.faa.chula.ac.th/department/show/56', note:'เปิดหน้าแผนกเพื่อดูหลักสูตรและประกาศรับสมัครฉบับล่าสุด' },
    { name:'มหาวิทยาลัยเกษตรศาสตร์', faculty:'คณะมนุษยศาสตร์ · ภาควิชาดนตรี', province:'กรุงเทพมหานคร', region:'bangkok', levels:'ปริญญาตรี', majors:['ดนตรีไทย','ดนตรีตะวันตก'], url:'https://human.ku.ac.th/curriculum/bachelors-degree/', extra:'https://music.human.ku.ac.th/bachelor.php', note:'หลักสูตรศิลปศาสตรบัณฑิต' },
    { name:'มหาวิทยาลัยศรีนครินทรวิโรฒ', faculty:'คณะศิลปกรรมศาสตร์', province:'กรุงเทพมหานคร', region:'bangkok', levels:'ปริญญาตรี', majors:['ดุริยางคศาสตร์สากล','ดนตรีศึกษา'], url:'https://fofa.swu.ac.th/th/images/FOFA/TQF_2558/T2_BFA_Music.pdf', extra:'https://fofa.swu.ac.th/th/images/FOFA/TQF_2557/T2_BED_Music_Education.pdf', note:'เอกสารหลักสูตรที่เผยแพร่มีอายุ ควรตรวจปีที่ยังเปิดรับกับคณะก่อนสมัคร' },
    { name:'มหาวิทยาลัยราชภัฏบ้านสมเด็จเจ้าพระยา', faculty:'วิทยาลัยการดนตรี', province:'กรุงเทพมหานคร', region:'bangkok', levels:'ปริญญาตรี–เอก', majors:['ดนตรีศึกษา','ดุริยางคศาสตร์'], url:'https://music.bsru.ac.th/curriculum/', note:'หน้าแสดงประเภทหลักสูตร; ตรวจชื่อสาขาย่อยในหน้าหลักสูตรก่อนสมัคร' },
    { name:'มหาวิทยาลัยรังสิต', faculty:'วิทยาลัยดนตรี', province:'ปทุมธานี', region:'central', levels:'ปริญญาตรี–โท', majors:['การแสดงดนตรี','การผลิตดนตรี','การประพันธ์เพลง','การขับร้อง'], url:'https://www2.rsu.ac.th/faculty/Music', note:'ปทุมธานี ใกล้กรุงเทพฯ; หน้าเจ้าของหลักสูตรมีแขนงคลาสสิก แจ๊ส และดนตรีสมัยนิยม' },
    { name:'มหาวิทยาลัยมหาสารคาม', faculty:'วิทยาลัยดุริยางคศิลป์', province:'มหาสารคาม', region:'northeast', levels:'ปริญญาตรี–เอก', majors:['ดุริยางคศาสตร์','ดนตรีศึกษา'], url:'https://music.msu.ac.th/?page_id=4222', note:'หน้าเจ้าของหลักสูตรแสดง ดศ.บ., กศ.บ., ปริญญาโทและเอก' },
    { name:'มหาวิทยาลัยขอนแก่น', faculty:'คณะศิลปกรรมศาสตร์', province:'ขอนแก่น', region:'northeast', levels:'ปริญญาตรี', majors:['ดุริยางคศาสตร์','ดนตรีศึกษา'], url:'https://fa.kku.ac.th/wp-content/uploads/2022/11/ข้อมูลหลักสูตร-ระดับปริญญาตรีหลักสูตรดุริยางคศาสตรบัณฑิต-.pdf', extra:'https://fa.kku.ac.th/wp-content/uploads/2024/12/3132_2567-FA-KKUSAT-68.pdf', note:'เอกสาร PDF หลักสูตรและประกาศรับสมัครเป็นคนละปีการศึกษา' },
    { name:'มหาวิทยาลัยพายัพ', faculty:'สาขาวิชาดุริยางคศาสตร์', province:'เชียงใหม่', region:'north', levels:'ปริญญาตรี', majors:['ดุริยางคศาสตร์'], url:'https://academic.payap.ac.th/pyu/uploads/userfiles/file/curiculum/tqf/tqf2_2565/MU_BA.pdf', note:'เอกสารหลักสูตร PDF ฉบับปี 2565; ตรวจสถานะปัจจุบันก่อนสมัคร' },
    { name:'มหาวิทยาลัยเชียงใหม่', faculty:'คณะศึกษาศาสตร์', province:'เชียงใหม่', region:'north', levels:'ปริญญาตรี', majors:['ดนตรีศึกษา'], url:'https://dctl.edu.cmu.ac.th/page/iedj6vbemaxf', extra:'https://www.edu.cmu.ac.th/news/7820-u55nxjdcyfsznyrgq1oj', note:'หลักสูตรใหม่; คณะยังประชาสัมพันธ์การรับนักศึกษาในปี 2569' },
    { name:'มหาวิทยาลัยทักษิณ', faculty:'คณะศิลปกรรมศาสตร์', province:'สงขลา', region:'south', levels:'ปริญญาตรี', majors:['ดุริยางคศาสตร์สากล','ดุริยางคศาสตร์ไทย'], url:'https://art.tsu.ac.th/menu.php?menu=16', note:'หน้าเจ้าของคณะแยกแขนงไทยและสากล' },
    { name:'มหาวิทยาลัยราชภัฏพระนครศรีอยุธยา', faculty:'คณะมนุษยศาสตร์และสังคมศาสตร์', province:'พระนครศรีอยุธยา', region:'central', levels:'ปริญญาตรี', majors:['ดนตรีศึกษา','ดนตรีสร้างสรรค์'], url:'https://www.aru.ac.th/human/?aru_code=2244&page=program&subpage=pro_course', extra:'https://www.aru.ac.th/index.php/tcas/view/49', note:'หลักสูตรดนตรีศึกษา 2567 และประกาศรับสมัครที่มีดนตรีสร้างสรรค์; ตรวจรอบปีที่จะสมัคร' },
    { name:'มหาวิทยาลัยราชภัฏมหาสารคาม', faculty:'คณะมนุษยศาสตร์และสังคมศาสตร์', province:'มหาสารคาม', region:'northeast', levels:'ปริญญาตรี', majors:['ดนตรี','ดนตรีไทยและดนตรีพื้นเมือง'], url:'https://husoc.rmu.ac.th/music-program/', extra:'https://e-admission.rmu.ac.th/plan-student/course/PORTFOLIO', note:'ชื่อแขนงอ้างอิงแผนรับสมัคร; ตรวจปีและรอบที่เปิดจริง' },
    { name:'มหาวิทยาลัยราชภัฏอุดรธานี', faculty:'คณะมนุษยศาสตร์และสังคมศาสตร์', province:'อุดรธานี', region:'northeast', levels:'ปริญญาตรี', majors:['ดนตรี'], url:'https://huso.udru.ac.th/หลักสูตร-สาขาวิชา/bachelor-of-fine-and-applied-arts-2/', note:'หลักสูตรศิลปกรรมศาสตรบัณฑิต สาขาดนตรี ฉบับปรับปรุง พ.ศ. 2569' },
    { name:'มหาวิทยาลัยราชภัฏนครราชสีมา', faculty:'คณะครุศาสตร์', province:'นครราชสีมา', region:'northeast', levels:'ปริญญาตรี', majors:['ดนตรีศึกษา'], url:'https://edu.nrru.ac.th/edubachelor/', note:'หน้าเจ้าของคณะระบุสาขาดนตรีระดับปริญญาตรี' },
    { name:'มหาวิทยาลัยราชภัฏกำแพงเพชร', faculty:'คณะครุศาสตร์', province:'กำแพงเพชร', region:'north', levels:'ปริญญาตรี', majors:['ดนตรีศึกษา'], url:'https://reg.kpru.ac.th/old/data/curkpru/2567/6715.pdf', note:'เอกสารหลักสูตรดนตรีศึกษา 4 ปี; ตรวจการรับสมัครปัจจุบันกับมหาวิทยาลัย' },
    { name:'มหาวิทยาลัยราชภัฏสวนสุนันทา', faculty:'คณะศิลปกรรมศาสตร์', province:'กรุงเทพมหานคร', region:'bangkok', levels:'ปริญญาตรี', majors:['ดนตรี'], url:'https://ssru.ac.th/education_faculty-finearts.php', extra:'https://cts.ssru.ac.th/File/IS/Announce/Files/x3aaj3du.pdf', note:'เอกสารรับสมัครที่พบเป็นเอกสารเก่า; ตรวจว่าหลักสูตรยังเปิดรับในปีล่าสุด' },
    { name:'มหาวิทยาลัยราชภัฏเชียงใหม่', faculty:'คณะครุศาสตร์ / คณะมนุษยศาสตร์และสังคมศาสตร์', province:'เชียงใหม่', region:'north', levels:'ปริญญาตรี', majors:['ดนตรีศึกษา','ดนตรีสากล'], url:'https://www.tcas.cmru.ac.th/cmrufolio2026/plan_intake.php', extra:'https://www.tcas.cmru.ac.th/cmrufolio2026/assets/notice_footer69.pdf', note:'แผนรับสมัครปี 2569 และเกณฑ์สอบดนตรีสากล; ตรวจปีสมัครล่าสุด' },
    { name:'มหาวิทยาลัยราชภัฏอุบลราชธานี', faculty:'คณะครุศาสตร์ / สายศิลปกรรม', province:'อุบลราชธานี', region:'northeast', levels:'ปริญญาตรี', majors:['ดนตรี','ดนตรีศึกษา'], url:'https://apr.ubru.ac.th/curriculum-structure2568/', note:'โครงสร้างหลักสูตรปีการศึกษา 2568 แยกดนตรี ศป.บ. และดนตรีศึกษา ค.บ.' },
    { name:'มหาวิทยาลัยราชภัฏนครศรีธรรมราช', faculty:'คณะครุศาสตร์', province:'นครศรีธรรมราช', region:'south', levels:'ปริญญาตรี', majors:['ดนตรีศึกษา'], url:'https://edu2.nstru.ac.th/wdps/สาขาวิชาดนตรีศึกษา/', note:'หน้าเจ้าของคณะระบุหลักสูตรครุศาสตรบัณฑิตสาขาดนตรีศึกษา' },
    { name:'มหาวิทยาลัยราชภัฏสุราษฎร์ธานี', faculty:'คณะมนุษยศาสตร์และสังคมศาสตร์', province:'สุราษฎร์ธานี', region:'south', levels:'ปริญญาตรี', majors:['ดนตรีสากล'], url:'https://human.sru.ac.th/programs/western-music/', note:'หน้าเจ้าของคณะระบุสาขาดนตรีสากล' },
    { name:'มหาวิทยาลัยบูรพา', faculty:'คณะดนตรีและการแสดง', province:'ชลบุรี', region:'east', levels:'ปริญญาตรี–โท', majors:['ดนตรีไทยและนาฏศิลป์สร้างสรรค์','ดนตรีและการแสดง'], url:'https://www.buu.ac.th/bachelor-degree/', extra:'https://grd.buu.ac.th/master-faculty-of-music-and-performing-arts/', note:'แยกหลักสูตรปริญญาตรีและโท; ตรวจสาขารับสมัครปีปัจจุบันบนหน้าเจ้าของมหาวิทยาลัย' },
    { name:'สถาบันดนตรีกัลยาณิวัฒนา', faculty:'สำนักวิชาดุริยางคศาสตร์', province:'กรุงเทพมหานคร', region:'bangkok', levels:'ปริญญาตรี–โท', majors:['ดุริยางคศาสตร์'], url:'https://www.pgvim.ac.th/programs/', extra:'https://www.pgvim.ac.th/admission/information_PortfolioA.php', note:'หลักสูตร B.M. เน้นการแสดงดนตรีคลาสสิก ทฤษฎีและการสร้างสรรค์' },
    { name:'มหาวิทยาลัยกรุงเทพธนบุรี', faculty:'คณะดุริยางคศาสตร์', province:'กรุงเทพมหานคร', region:'bangkok', levels:'ปริญญาตรี–เอก', majors:['ดุริยางคศาสตร์','ดนตรีศึกษา'], url:'https://bkkthon.ac.th/home/th/faculty/faculty-13/department-26/curriculum', note:'หน้าเจ้าของคณะแสดง ดศ.บ., ศษ.บ., ดศ.ม. และ ปร.ด.' }
  ];
  const schools = [
    { name:'Yamaha Music School', area:'หลายเขตในกรุงเทพฯ', type:'เครือข่ายโรงเรียน', genres:['พื้นฐาน','คลาสสิก','ป๊อป'], url:'https://th.yamaha.com/th/education/', locator:'https://th.yamaha.com/th/education/school-locator/music-school-new.html', note:'ใช้ตัวค้นหาสาขาทางการเลือกกรุงเทพฯ; ตัวเลข 90+ เป็นเครือข่ายทั่วประเทศ ไม่ใช่จำนวนในกรุงเทพฯ' },
    { name:'MelodyPlus', area:'พระราม 3 · วัชรพล · ปิ่นเกล้า · บางนา', type:'โรงเรียนหลายสาขา', genres:['คลาสสิก','แจ๊ส','ป๊อป','ดนตรีไทย','เด็กเล็ก'], url:'https://melodyplusmusic.com/', branches:['Terminal 21 พระราม 3','Lotus วัชรพล','Central ปิ่นเกล้า','Central บางนา'], note:'เว็บโรงเรียนระบุ 5 สาขารวมสาขาแคราย จ.นนทบุรี; การ์ดนี้แสดงเฉพาะย่านในกรุงเทพฯ' },
    { name:'School of Rock Thailand', area:'คลองสามวา', type:'โรงเรียน / เรียนรวมวง', genres:['ร็อก','ป๊อป','รวมวง'], url:'https://www.schoolofrockthailand.com/', note:'เว็บโรงเรียนระบุการเรียนเดี่ยว รวมวง บันทึกเสียงและแสดงสด' },
    { name:'SCA Superstar Academy', area:'ทองหล่อ', type:'วิทยาลัย / คอร์สระยะสั้น', genres:['ป๊อป','ร็อก','แจ๊ส','รวมวง'], url:'https://www.scacollege.ac.th/academic/superstaracademy/band-program/', note:'คอร์สวงดนตรีระบุ Pop, Rock, R&B, Soul และ Jazz Fusion' },
    { name:'PlaySound', area:'12 สาขาที่หน้าเจ้าของระบุว่าอยู่ในกรุงเทพฯ', type:'โรงเรียนหลายสาขา', genres:['พื้นฐาน','ป๊อป','คลาสสิก'], url:'https://www.playsoundbkk.com/contact.html', branches:['วัชรพล','เดอะซีน ทาวน์อินทาวน์','อินเด็กซ์ พระราม 2','อินเด็กซ์ บางนา','แบมบินี่ วิลล่า สุขุมวิท 26','เดอะ พาซิโอ พาร์ค กาญจนาภิเษก','เดอะสตรีท รัชดา','มัยลาภ–รามอินทรา 14','ดิอัพ พระราม 3','เดอะ แร็กเก็ต คลับ สุขุมวิท 49','มาร์เช่ กรุงเทพกรีฑา','สัมมากรเพลส รามคำแหง'], note:'คัดเฉพาะ 12 สาขาที่หน้าเจ้าของระบุที่อยู่กรุงเทพฯ; ไม่นับสาขานนทบุรี ปทุมธานี และชลบุรี' },
    { name:'Muse Music Academy', area:'เจริญนคร · บางแค', type:'โรงเรียนหลายสาขา', genres:['พื้นฐาน','ป๊อป','คลาสสิก'], url:'https://www.musemusicacademy.com/contact-us', branches:['ICS เจริญนคร','The Mall บางแค'], note:'หน้าโรงเรียนระบุสองสาขาพร้อมลิงก์แผนที่โดยตรง; ตรวจคอร์สกับสาขา' },
    { name:'Bangkok Bravo! School of Music', area:'พระราม 2', type:'โรงเรียนดนตรี', genres:['คลาสสิก','ป๊อป','แจ๊ส'], url:'https://www.thebright.co.th/tenant/bangkokbravo/', note:'หน้าเจ้าของพื้นที่ระบุเปียโน ร้อง ไวโอลิน กีตาร์ เบส กลอง แซกโซโฟนและทฤษฎี' },
    { name:'Hibiki Music Studio', area:'หอศิลปกรุงเทพฯ · ปทุมวัน', type:'สตูดิโอ / โรงเรียน', genres:['คลาสสิก','แจ๊ส'], url:'https://www.bacc.or.th/en/directories/62258', note:'หน้าเจ้าของอาคารระบุเปียโน ไวโอลิน กีตาร์และแจ๊ส; โปรดโทรตรวจสถานะร้านก่อนเดินทาง' },
    { name:'Royal Bangkok Symphony Music School', area:'ใกล้สวนลุมพินี · ปทุมวัน', type:'โรงเรียนดนตรี', genres:['คลาสสิก','แจ๊ส','ป๊อป'], url:'https://www.rbsothailand.com/courses/', note:'หน้าโรงเรียนระบุเครื่องดนตรีออร์เคสตรา เปียโน กีตาร์คลาสสิก ร้องเพลง ทฤษฎีและโสตทักษะ; ต้องตรวจพินและตารางเรียนล่าสุดก่อนเดินทาง' },
    { name:'MCGP Music Mahidol', area:'สยามพารากอน · ปทุมวัน / ซีคอนสแควร์ · ประเวศ', type:'ศูนย์ดนตรีสำหรับบุคคลทั่วไป', genres:['พื้นฐาน','คลาสสิก','แจ๊ส','ป๊อป','ดนตรีไทย','เด็กเล็ก'], url:'https://www.mcgp-music-mahidol.com/contact-us', branches:['สยามพารากอน','ซีคอนสแควร์ ศรีนครินทร์'], note:'หน้าเจ้าของศูนย์ระบุที่อยู่สองสาขาและคอร์สหลายแนว; ตรวจรอบเรียนของแต่ละสาขาก่อนสมัคร' },
    { name:'Bangkok Learning City · ดนตรีไทย', area:'18 จุดเรียนตามหน้าคอร์สของ กทม.', type:'คอร์สสาธารณะ', genres:['ดนตรีไทย'], url:'https://learning.bangkok.go.th/course/lc-0137/', branches:['ศูนย์นันทนาการสะพานสูง','ศูนย์นันทนาการสะพานพระราม 8','ศูนย์นันทนาการดอนเมือง','โรงเรียนฝึกอาชีพกรุงเทพมหานคร หนองจอก','ศูนย์นันทนาการเตชะวณิช','ศูนย์นันทนาการคลองสามวา','ศูนย์นันทนาการวัดธาตุทอง','ศูนย์นันทนาการวัดเวฬุราชิณ','ศูนย์นันทนาการวัดดอกไม้','ศูนย์นันทนาการบางแค เรืองสอน','ศูนย์นันทนาการบ่อนไก่','ศูนย์นันทนาการเกียกกาย','ศูนย์นันทนาการคลองเตย','ศูนย์นันทนาการจตุจักร','ศูนย์นันทนาการมีนบุรี','ศูนย์นันทนาการลาดกระบัง','ศูนย์นันทนาการจอมทอง','ศูนย์นันทนาการบางนา'], note:'คอร์สภาครัฐ ไม่ใช่โรงเรียนเอกชน; หน้า กทม. ระบุสถานที่สอน 18 แห่ง ต้องตรวจรอบล่าสุดที่ต้นทาง' }
  ];
  root.MILInstitutions = { universities, schools };
  if (typeof module !== 'undefined' && module.exports) module.exports = { universities, schools };
})(typeof window !== 'undefined' ? window : globalThis);
