(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.MILPortal=api})(typeof window!=='undefined'?window:globalThis,function(){
  const checked='25 ก.ย. 2569';
  const resources=[
    {id:'chrome-lab',name:'Chrome Music Lab',owner:'Google Chrome Experiments',url:'https://musiclab.chromeexperiments.com/',source:'https://musiclab.chromeexperiments.com/',category:'try',goal:'ลองจังหวะ ทำนอง และสร้างเพลงสั้นแบบเล่นได้ทันที',first:'เปิด Song Maker แล้วลองวางเสียง 8 ช่อง',cost:'free',costText:'ฟรี',account:'ไม่ต้องสมัคร',device:'เว็บบนมือถือ/คอม',language:'อังกฤษ (ข้อความน้อย)',thai:false,noInstrument:true,checked,note:'เหมาะกับการทดลองครั้งแรก; ไม่ใช่คอร์สฝึกเครื่องดนตรี'},
    {id:'ableton',name:'Learning Music',owner:'Ableton',url:'https://learningmusic.ableton.com/',source:'https://learningmusic.ableton.com/',category:'try',goal:'เข้าใจ beat, melody และการประกอบเพลงผ่าน browser',first:'เริ่มบท Make beats แล้วลองเปิด–ปิดเสียงตามจังหวะ',cost:'free',costText:'เปิดบทเรียนได้ฟรี',account:'ไม่ต้องมีเครื่องดนตรี',device:'เว็บบนคอม/มือถือ',language:'อังกฤษ',thai:false,noInstrument:true,checked,note:'เว็บระบุว่าไม่ต้องมีประสบการณ์หรืออุปกรณ์ก่อน'},
    {id:'theory-lessons',name:'Lessons',owner:'musictheory.net',url:'https://www.musictheory.net/lessons',source:'https://www.musictheory.net/lessons',category:'foundation',goal:'เรียนโน้ต จังหวะ สเกล และหลักดนตรีตามหัวข้อ',first:'เริ่ม Note Duration หรือ The Staff ตามพื้นฐานของตน',cost:'free',costText:'ฟรี',account:'ไม่จำเป็นสำหรับบทเรียนเว็บ',device:'เว็บบนมือถือ/คอม',language:'อังกฤษ',thai:false,noInstrument:true,checked,note:'เว็บไซต์ระบุว่าบทเรียนออนไลน์ใช้ฟรี'},
    {id:'theory-exercises',name:'Exercises',owner:'musictheory.net',url:'https://www.musictheory.net/exercises',source:'https://www.musictheory.net/exercises',category:'foundation',goal:'ฝึกอ่านโน้ต คีย์บอร์ด fretboard และการฟัง',first:'เลือก Note Identification หรือ Ear Training ที่เหมาะกับเป้าหมาย',cost:'free',costText:'ฟรี',account:'ไม่จำเป็นสำหรับแบบฝึกเว็บ',device:'เว็บบนมือถือ/คอม',language:'อังกฤษ',thai:false,noInstrument:true,checked,note:'ครูสามารถสร้างลิงก์แบบฝึกเฉพาะหัวข้อได้'},
    {id:'bandlab',name:'BandLab Studio',owner:'BandLab',url:'https://www.bandlab.com/',source:'https://help.bandlab.com/hc/en-us/articles/115002945153-Getting-Started-with-the-BandLab-Studio',category:'create',goal:'อัดเสียง ตัดต่อ และมิกซ์เดโมเพลงด้วยมือถือหรือ browser',first:'อ่านคู่มือเริ่มต้น แล้วสมัครเพื่อสร้าง New Project',cost:'free',costText:'Studio ฟรี',account:'ต้องสมัครก่อนสร้างงาน',device:'เว็บ/มือถือ',language:'อังกฤษเป็นหลัก',thai:false,noInstrument:true,checked,note:'การทำโปรเจกต์ต้องมีบัญชี; ตรวจสิทธิของเสียงก่อนเผยแพร่'},
    {id:'musescore',name:'MuseScore Studio',owner:'MuseScore',url:'https://musescore.org/en',source:'https://musescore.org/en',category:'create',goal:'เขียนโน้ตและเรียบเรียงเพลงบนคอมพิวเตอร์',first:'อ่านความต้องการระบบแล้วดาวน์โหลด MuseScore Studio',cost:'free',costText:'โปรแกรมฟรี',account:'ไม่ต้องสมัครเพื่อใช้ตัวโปรแกรม',device:'ต้องติดตั้งบนคอม',language:'หลายภาษา/คู่มืออังกฤษ',thai:false,noInstrument:true,checked,note:'แยกจากบริการโน้ตบน musescore.com ซึ่งมีเงื่อนไขต่างกัน'},
    {id:'musora',name:'Guitareo on Musora',owner:'Musora',url:'https://www.musora.com/guitar',source:'https://www.musora.com/choose-trial',category:'practice',goal:'เรียนกีตาร์ตามลำดับบทพร้อมคำแนะนำการฝึก',first:'ดูตัวอย่าง method ก่อนตัดสินใจทดลองสมาชิก',cost:'paid',costText:'ทดลองใช้ฟรี 7 วัน แล้วมีค่าสมาชิก',account:'ทดลองต้องใช้อีเมลและบัตร',device:'เว็บ/แอป',language:'อังกฤษ',thai:false,noInstrument:false,checked,note:'ตรวจราคาและวันตัดเงินที่หน้าเจ้าของบริการก่อนสมัคร'},
    {id:'samt',name:'ค้นหาครูดนตรี',owner:'SAMT Music',url:'https://www.mysamt.com/',source:'https://www.mysamt.com/',category:'teacher',goal:'ค้นครูดนตรีในไทยตามวิชาและพื้นที่',first:'เลือกวิชาและพื้นที่ แล้วเทียบวิธีสอน ราคา และเงื่อนไข',cost:'varies',costText:'ค้นหาได้; ค่าเรียนตามครู',account:'ตรวจขั้นตอนกับผู้ให้บริการ',device:'เว็บบนมือถือ/คอม',language:'ไทย',thai:true,noInstrument:false,checked,note:'เป็นบริการของบุคคลภายนอก ราคา/เวลาต้องยืนยันกับครู'},
    {id:'chula-mooc',name:'ดนตรีบำบัดเบื้องต้น',owner:'CHULA MOOC',url:'https://mooc.chula.ac.th/course-detail/76',source:'https://mooc.chula.ac.th/course-detail/76',category:'pathway',goal:'สำรวจบทบาทและพื้นฐานการทำงานของนักดนตรีบำบัด',first:'อ่านรายละเอียดและตรวจว่ารอบเรียนเปิดหรือไม่',cost:'free',costText:'MOOC เปิดเรียนฟรี; ตรวจรอบ',account:'อาจต้องสมัครเพื่อเรียน',device:'เว็บบนมือถือ/คอม',language:'ไทย',thai:true,noInstrument:true,checked,note:'คอร์สสำรวจอาชีพ ไม่ใช่ใบอนุญาตประกอบวิชาชีพ'},
    {id:'thai-mooc',name:'ศิลปกรรมท้องถิ่นชายแดนใต้',owner:'Thai MOOC / มหาวิทยาลัยสงขลานครินทร์',url:'https://thaimooc.ac.th/courses/course-v1psu005200/',source:'https://thaimooc.ac.th/courses/course-v1psu005200/',category:'culture',goal:'เรียนรู้ศิลปะ ดนตรี และการแสดงท้องถิ่นชายแดนใต้',first:'อ่านหัวข้อรายวิชาและตรวจสถานะการลงทะเบียน',cost:'free',costText:'รายวิชาใน Thai MOOC; ตรวจเงื่อนไข',account:'อาจต้องสมัครเพื่อเรียน',device:'เว็บบนมือถือ/คอม',language:'ไทย',thai:true,noInstrument:true,checked,note:'เน้นภาพรวมวัฒนธรรม ไม่ใช่การฝึกเล่นเครื่องแบบตัวต่อตัว'},
    {id:'mahidol',name:'หลักสูตรและการรับเข้า',owner:'วิทยาลัยดุริยางคศิลป์ มหาวิทยาลัยมหิดล',url:'https://www.music.mahidol.ac.th/admissions/',source:'https://www.music.mahidol.ac.th/admissions/',category:'pathway',goal:'ดูเส้นทางก่อนอุดมศึกษา ปริญญาตรี และบัณฑิตศึกษา',first:'เลือกช่วงการศึกษาแล้วเปิดคู่มือรับสมัครปีปัจจุบัน',cost:'varies',costText:'มีค่าสมัคร/ค่าเรียนตามประกาศ',account:'สมัครเมื่อยื่นจริง',device:'เว็บบนมือถือ/คอม',language:'ไทย/อังกฤษบางหน้า',thai:true,noInstrument:false,checked,note:'ข้อกำหนดและวันรับสมัครเปลี่ยนตามปี อย่ายึดข้อมูลจากการ์ดนี้แทนประกาศล่าสุด'}
  ];
  resources.find(r=>r.id==='theory-lessons').category='theory';
  resources.find(r=>r.id==='theory-exercises').category='theory';
  resources.find(r=>r.id==='bandlab').category='recording';
  resources.find(r=>r.id==='musescore').category='notation';
  const more=[
    ['soundbrenner','The Metronome by Soundbrenner','Soundbrenner','https://apps.apple.com/us/app/the-metronome-by-soundbrenner/id1048954353','metronome','ฝึกจังหวะด้วย tempo, accent และ subdivision','ตั้ง 60 BPM แล้วตบมือหนึ่งครั้งต่อคลิก','freemium','ดาวน์โหลดฟรี; มีการซื้อในแอป','ตรวจใน App Store','iPhone/iPad','อังกฤษ',false,true,'คุณสมบัติบางส่วนอยู่ในแผน Plus'],
    ['tonalenergy','TonalEnergy Tuner & Metronome','TonalEnergy','https://apps.apple.com/us/app/tonalenergy-tuner-metronome/id497716362','tuner','ตั้งเสียง ฝึก intonation และจังหวะในเครื่องมือเดียว','เลือกเครื่องดนตรีแล้วเล่นโน้ตยาวเทียบเข็มเสียง','paid','แอปเสียเงิน; ราคาในไทยอาจต่าง','ซื้อผ่าน App Store','iPhone/iPad','อังกฤษ',false,false,'เหมาะกับเครื่องลม เครื่องสาย และเสียงร้อง; ตรวจราคาปัจจุบัน'],
    ['guitartuna','GuitarTuna','Yousician','https://apps.apple.com/us/app/guitartuna-tune-play-guitar/id527588389','tuner','ตั้งสายกีตาร์ อูคูเลเล่ เบส และเครื่องสาย','อนุญาตไมโครโฟนแล้วดีดสายทีละเส้น','freemium','ดาวน์โหลดฟรี; มีสมาชิก/การซื้อในแอป','ตรวจใน App Store','iPhone/iPad','อังกฤษ/หลายภาษา',false,false,'ต้องมีเครื่องจริงและที่ค่อนข้างเงียบ'],
    ['moises','Moises','Moises','https://apps.apple.com/us/app/moises-the-musicians-app/id1515796612','practice','แยกเสียงร้อง/เครื่องดนตรี ปรับความเร็วและคีย์เพื่อซ้อม','นำเข้าเพลงที่มีสิทธิใช้ แล้วลดเสียงส่วนที่ต้องการฝึก','freemium','ดาวน์โหลดฟรี; มีการซื้อในแอป','ตรวจใน App Store','iPhone/iPad','อังกฤษ/หลายภาษา',false,false,'ผลแยกเสียงขึ้นกับไฟล์ต้นฉบับและสิทธิการใช้เพลง'],
    ['anytune','Anytune','Anytune Inc.','https://apps.apple.com/us/app/anytune-transcribe-practice/id415365180','practice','ชะลอเพลง วนท่อน และปรับคีย์เพื่อแกะเพลง','นำเข้าไฟล์เพลงของตนแล้วกำหนด A-B loop','freemium','ดาวน์โหลดฟรี; มีการซื้อในแอป','ตรวจใน App Store','iPhone/iPad','อังกฤษ',false,false,'ตรวจรูปแบบไฟล์ที่นำเข้าได้และสิทธิการใช้'],
    ['ireal','iReal Pro','Technimo LLC','https://apps.apple.com/us/app/ireal-pro/id298206806','practice','ฝึกคอร์ดกับวงประกอบจำลองและเปลี่ยน tempo/คีย์','เลือกมาตรฐานคอร์ดแล้วลองช้าก่อน','paid','แอปเสียเงิน; ราคาในไทยอาจต่าง','ซื้อผ่าน App Store','iPhone/iPad','อังกฤษ',false,false,'เป็น chord chart/backing track ไม่ใช่ไฟล์เสียงเพลงต้นฉบับ'],
    ['tenuto','Tenuto','musictheory.net','https://apps.apple.com/us/app/tenuto/id459313476','theory','ฝึกอ่านโน้ต คอร์ด สเกล และการฟังแบบปรับโจทย์ได้','เลือก exercise เดียวแล้วตั้งช่วงเสียงให้พอดี','paid','แอปเสียเงิน; เว็บ musictheory.net มีแบบฝึกฟรี','ซื้อผ่าน App Store','iPhone/iPad','อังกฤษ',false,true,'ใช้เว็บฟรีก่อนตัดสินใจซื้อแอปได้'],
    ['garageband','GarageBand for iOS','Apple','https://apps.apple.com/us/app/garageband/id408709785','songwriting','บันทึกไอเดียด้วย Touch Instruments, Live Loops และหลายแทร็ก','เปิด Live Loops แล้วอัดร่างเพลง 30 วินาที','free','ดาวน์โหลดฟรี','ใช้ Apple ID ตามข้อกำหนด App Store','iPhone/iPad','หลายภาษา',false,true,'ใช้ได้เฉพาะอุปกรณ์ Apple ที่รองรับ'],
    ['hookpad','Hookpad','Hooktheory','https://www.hooktheory.com/hookpad','songwriting','ลองคอร์ดและทำนองใน sketchpad สำหรับแต่งเพลง','เปิดคู่มือแล้ววาง 4 คอร์ดกับทำนองสั้น','varies','ตรวจแผนและราคาที่เว็บผู้พัฒนา','ตรวจแผนที่เว็บ','เว็บบนคอม','อังกฤษ',false,true,'ข้อจำกัดและราคาเปลี่ยนตามแผน'],
    ['songbook','SongBook Chordpro','LinkeSOFT','https://apps.apple.com/us/app/songbook-chordpro/id392888837','performance','เก็บ chord/lyrics และสร้าง setlist สำหรับเล่นจริง','นำเข้าเพลงที่ตนมีสิทธิ แล้วรวมเป็น setlist','paid','แอปเสียเงิน; ตรวจราคาในไทย','ซื้อผ่าน App Store','iPhone/iPad','อังกฤษ',false,false,'เนื้อเพลงและคอร์ดมีเรื่องลิขสิทธิ์; ใช้ไฟล์ที่มีสิทธิ'],
    ['forscore','forScore','forScore LLC','https://apps.apple.com/us/app/forscore/id363738376','performance','อ่านและจดโน้ต PDF จัด setlist ระหว่างซ้อมหรือขึ้นเวที','นำเข้า PDF ที่มีสิทธิแล้วลองจด cue ลงบนโน้ต','paid','ตรวจราคา/แผนที่ App Store','ซื้อผ่าน App Store','iPad/iPhone','อังกฤษ',false,false,'เหมาะกับจอแท็บเล็ต; ต้องมีโน้ตที่ใช้ได้อย่างถูกสิทธิ'],
    ['audacity','Audacity','Muse Group / Audacity','https://www.audacityteam.org/','recording','อัดเสียงและตัดต่อไฟล์เสียงบนคอม','ติดตั้งจากเว็บทางการแล้วอัดคลิปทดลอง 30 วินาที','free','ฟรีและโอเพนซอร์ส','ไม่ต้องสมัคร','คอม Windows/macOS/Linux','หลายภาษา',false,true,'ไม่มีแอป iOS/Android ทางการ; ระวังแอปเลียนชื่อ'],
    ['reaper','REAPER','Cockos','https://www.reaper.fm/','recording','เรียน workflow การอัด มิกซ์ และส่งออกเพลงหลายแทร็ก','ดาวน์โหลดเวอร์ชันทดลองแล้วอัด 2 แทร็ก','trial','ทดลองเต็มฟังก์ชัน 60 วัน แล้วซื้อไลเซนส์','ไม่ต้องสมัครเพื่อทดลอง','คอม Windows/macOS/Linux','อังกฤษ',false,true,'หลังระยะทดลองต้องซื้อไลเซนส์ที่เหมาะสม'],
    ['ableton-live','Ableton Live','Ableton','https://www.ableton.com/en/live/what-is-live/','recording','สร้างเพลงและเตรียมการแสดงด้วย Session/Arrangement View','ดูภาพรวม workflow แล้วลองชุดทดลองทางการ','trial','มีระยะทดลอง; ใช้ต่อมีค่าไลเซนส์','ตรวจบัญชี/การทดลองกับผู้พัฒนา','คอม Windows/macOS','อังกฤษ/หลายภาษา',false,true,'สเปกคอมและราคาแตกต่างตามรุ่น'],
    ['dorico-se','Dorico SE','Steinberg','https://www.steinberg.net/dorico/se/','notation','เขียนโน้ตและจัดหน้า score บนคอม','ติดตั้ง SE แล้วสร้าง score สำหรับวงเล็ก','free','รุ่น SE ฟรี','อาจต้องมีบัญชี Steinberg','คอม Windows/macOS','อังกฤษ/หลายภาษา',false,true,'รุ่นฟรีจำกัดจำนวนผู้เล่น; ตรวจขีดจำกัดล่าสุด'],
    ['logic-ipad','Logic Pro for iPad','Apple','https://apps.apple.com/us/app/logic-pro-make-music/id1615087040','recording','ทำเพลงและมิกซ์บน iPad ด้วยเครื่องมือระดับโปร','ดูอุปกรณ์ที่รองรับและแผนก่อนเริ่มโปรเจกต์','subscription','ดาวน์โหลดได้; การใช้เต็มรูปแบบตามแผนสมาชิก','ใช้ Apple ID/แผนสมาชิก','iPad รุ่นที่รองรับ','หลายภาษา',false,true,'ตรวจแผน ราคา และอุปกรณ์ที่รองรับในประเทศ'],
    ['qlab','QLab','Figure 53','https://qlab.app/download/','performance','จัดลำดับคิวเสียง วิดีโอ และแสงสำหรับการแสดง','สร้าง workspace แล้วเพิ่ม audio cue ทดลองหนึ่งไฟล์','freemium','ฟังก์ชันพื้นฐานใช้ฟรี; ขั้นสูงมีไลเซนส์','ไม่ต้องซื้อเพื่อใช้พื้นฐาน','คอม macOS','อังกฤษ',false,true,'ใช้ macOS และต้องทดสอบ cue/อุปกรณ์ก่อนแสดงจริง'],
    ['soundslice','Soundslice','Soundslice','https://www.soundslice.com/','practice','ดูโน้ต/แท็บที่ซิงก์กับเสียงหรือวิดีโอและวนท่อนซ้อม','เปิดตัวอย่างที่ถูกสิทธิแล้วลด tempo ของท่อนสั้น','freemium','มีแผนฟรีและฟีเจอร์เสียเงิน; ตรวจล่าสุด','อาจต้องสมัครเพื่อบันทึกงาน','เว็บบนคอม/มือถือ','อังกฤษ',false,false,'เนื้อหาที่นำเข้าและแชร์ต้องมีสิทธิใช้'],
    ['flat','Flat','Tutteo','https://flat.io/','notation','เขียนโน้ตออนไลน์และทำงานร่วมกัน','สร้าง score สั้น 4 ห้อง แล้วลองแชร์กับครู','freemium','มีแผนฟรีและเสียเงิน; ตรวจล่าสุด','ต้องสมัครเพื่อบันทึก/แชร์','เว็บบนคอม/มือถือ','อังกฤษ',false,true,'จำนวน score และฟังก์ชันอาจจำกัดตามแผน']
  ];
  for(const [id,name,owner,url,category,goal,first,cost,costText,account,device,language,thai,noInstrument,note] of more){resources.push({id,name,owner,url,source:url,category,goal,first,cost,costText,account,device,language,thai,noInstrument,checked,note})}
  const pro=[
    ['pro-tools','Pro Tools','Avid','https://www.avid.com/pro-tools','recording','อัด ตัดต่อ และมิกซ์งานสตูดิโอหลายแทร็ก','ดู Pro Tools Intro แล้วลองจัด session และ comp เสียง','freemium','มี Intro ฟรี; รุ่นงานอาชีพมีค่าไลเซนส์','ต้องมีบัญชี Avid สำหรับดาวน์โหลด/ไลเซนส์','คอม Windows/macOS','อังกฤษ',false,true,'ตรวจสเปก/แผนและรูปแบบไฟล์ที่สตูดิโอคู่ค้าใช้'],
    ['logic-mac','Logic Pro for Mac','Apple','https://apps.apple.com/us/app/logic-pro/id634148309','songwriting','แต่งเพลง อัด MIDI/audio และมิกซ์บน Mac','ลอง GarageBand ก่อน แล้วดู workflow Logic Pro บน Mac','paid','แอป Mac เสียเงิน; ตรวจราคาไทย','ซื้อผ่าน Mac App Store','Mac รุ่นที่รองรับ','หลายภาษา',false,true,'ใช้ได้บน Mac; ตรวจเวอร์ชันระบบและอุปกรณ์'],
    ['dorico-pro','Dorico Pro','Steinberg','https://www.steinberg.net/dorico/','notation','ทำ score และ part ระดับเผยแพร่หรือส่งให้วงเล่น','เริ่ม Dorico SE แล้วทดลองงานวงใหญ่ใน Pro','trial','มี trial ของ Pro; ใช้ต่อมีค่าไลเซนส์','ต้องมีบัญชี Steinberg','คอม Windows/macOS','อังกฤษ/หลายภาษา',false,true,'รุ่น SE กับ Pro มีขีดจำกัดต่างกัน; ตรวจเงื่อนไข trial'],
    ['sibelius','Sibelius','Avid','https://www.avid.com/sibelius','notation','เขียน score/part และส่งงานให้ทีมที่ใช้ Sibelius','ตรวจรูปแบบไฟล์ที่ผู้ร่วมงานใช้ แล้วลองรุ่นที่เหมาะ','subscription','มีหลายแผนและไลเซนส์; ตรวจราคาไทย','ต้องมีบัญชี Avid/ไลเซนส์','คอมและมือถือรุ่นที่รองรับ','อังกฤษ',false,true,'การร่วมงานต้องตกลงเวอร์ชันและรูปแบบไฟล์'],
    ['mainstage','MainStage','Apple','https://apps.apple.com/us/app/mainstage/id634159523','performance','ใช้ Mac เป็นชุดเสียง/เอฟเฟกต์สำหรับเล่นคีย์บอร์ดและเครื่องดนตรีสด','สร้าง concert แล้วทดสอบ patch change กับอุปกรณ์จริง','paid','แอป Mac เสียเงิน; ตรวจราคาไทย','ซื้อผ่าน Mac App Store','Mac + controller/audio interface ตามงาน','อังกฤษ/หลายภาษา',false,false,'ต้องทดสอบ rig และสำรองทางออกก่อนเล่นสด']
  ];
  for(const [id,name,owner,url,category,goal,first,cost,costText,account,device,language,thai,noInstrument,note] of pro){resources.push({id,name,owner,url,source:url,category,goal,first,cost,costText,account,device,language,thai,noInstrument,checked,note})}
  const g=(what,steps,best,limit,next)=>({what,steps,best,limit,next});
  const guides={
    'chrome-lab':g('หน้ารวมกิจกรรมทดลองเสียง เช่น Song Maker, Rhythm และ Spectrogram ที่กดเล่นได้ใน browser',['เลือก Song Maker','วางจังหวะ 4 ห้องและทำนอง 3 โน้ต','ฟังซ้ำแล้วเปลี่ยนหนึ่งองค์ประกอบ'], 'เด็ก ผู้เริ่มต้น และผู้ที่ยังไม่มีเครื่องดนตรี','เป็นการทดลองแนวคิดดนตรี ไม่สอนเทคนิคเครื่องดนตรีเป็นลำดับ','ถ้าชอบทำ beat ให้ต่อ Learning Music; ถ้าชอบทำนองให้ลอง GarageBand'),
    ableton:g('บทเรียนโต้ตอบเรื่อง beat, notes, scales, chords และ song structure',['เริ่ม Make beats','ลองเปลี่ยนจังหวะและฟังความต่าง','จดหนึ่งรูปแบบที่อยากนำไปทำเพลง'], 'ผู้เริ่มทำเพลงที่อยากเข้าใจองค์ประกอบก่อนใช้ DAW','เนื้อหาเป็นอังกฤษ และไม่แทนการฝึกเครื่องดนตรีจริง','นำ beat ที่ชอบไปสร้างร่างเพลงใน BandLab'),
    'theory-lessons':g('บทเรียนเรียงหัวข้อเรื่อง staff, duration, scales, intervals, chords และ rhythm',['ประเมินว่าตนอ่าน staff ได้หรือยัง','เลือกบทสั้น 1 เรื่อง','อธิบายสิ่งที่เพิ่งเรียนด้วยตัวอย่างหนึ่งห้องเพลง'], 'ผู้เริ่มอ่านโน้ตและครูที่ต้องการบทอ้างอิง','เป็นภาษาอังกฤษและเน้นทฤษฎีตะวันตก','ทำแบบฝึกใน Exercises หัวข้อเดียวกัน'),
    'theory-exercises':g('แบบฝึกระบุโน้ต คีย์ คอร์ด fretboard และ ear training ที่ปรับโจทย์ได้',['เลือกทักษะเดียว','ตั้งช่วงโน้ตให้สอดคล้องกับระดับ','ทำ 10 ข้อแล้วจดข้อผิดพลาดซ้ำ'], 'คนที่ต้องการวัดทักษะเฉพาะจุดและครูที่แชร์แบบฝึก','อย่าตั้งช่วงโจทย์กว้างเกินก่อนมีพื้นฐาน','กลับไปอ่าน Lessons เฉพาะเรื่องที่ผิดบ่อย'),
    bandlab:g('หน้า Studio สำหรับสร้างโปรเจกต์หลายแทร็ก อัดเสียง และมิกซ์บนเว็บหรือมือถือ',['อ่านคู่มือเริ่มต้นของ BandLab','สมัครบัญชีและเปิด New Project','อัดเสียง 20 วินาทีแล้วเพิ่มอีกหนึ่งแทร็ก'], 'ผู้เริ่มแต่งเพลงและกลุ่มที่ต้องการทำเดโมด้วยอุปกรณ์ที่มี','ต้องมีบัญชีและอินเทอร์เน็ต; ตรวจสิทธิของเสียงที่ใช้','ถ้าต้องการตัดต่อเสียงละเอียดบนคอม ลอง Audacity หรือ REAPER'),
    musescore:g('โปรแกรมเขียนโน้ตติดตั้งบนคอม พร้อมการเล่นกลับและการจัดพาร์ต',['ดาวน์โหลดจาก musescore.org','สร้าง score เครื่องเดียว 4 ห้อง','ใส่ตัวโน้ตและส่งออก PDF ทดลอง'], 'ผู้เรียน composition, arrangement และครูที่ทำโน้ต','โปรแกรม MuseScore Studio ต่างจากเว็บไซต์ musescore.com ที่มีเงื่อนไขเนื้อหา','ถ้าต้องการร่วมแก้โน้ตบนเว็บ ให้ดู Flat'),
    musora:g('บทเรียนกีตาร์แบบลำดับขั้น วิดีโอ และแผนการฝึก',['ดูหน้า course/method','เช็กแผนทดลองและวันเริ่มคิดเงิน','ลองบทแรกพร้อมจับเครื่องจริง'], 'ผู้เริ่มกีตาร์ที่ต้องการคอร์สต่อเนื่อง','ทดลองใช้ต้องตรวจเงื่อนไขบัตรและการต่ออายุ','ถ้าต้องการ feedback รายบุคคล ให้เทียบครูไทยใน SAMT'),
    samt:g('หน้าค้นหาครู/วิชาดนตรีในไทยตามพื้นที่และรูปแบบการสอน',['เลือกเครื่องดนตรีหรือวิชา','เทียบครู 2–3 คนตามพื้นที่ ราคา ประสบการณ์','สอบถามคาบทดลองและเป้าหมายก่อนตกลง'], 'ผู้เรียนที่ต้องการครูจริงหรือการเรียนในพื้นที่','ข้อมูล ราคา เวลา และคุณสมบัติครูต้องยืนยันกับผู้ให้บริการ','เตรียมเป้าหมาย 4 สัปดาห์ก่อนพบครู'),
    'chula-mooc':g('รายละเอียดคอร์สภาษาไทยเกี่ยวกับพื้นฐานดนตรีบำบัดและการประยุกต์',['อ่านผลลัพธ์การเรียน','ตรวจรอบเปิดและเงื่อนไขลงทะเบียน','จดคำถามเรื่องบทบาทวิชาชีพ'], 'ผู้สำรวจเส้นทางอาชีพดนตรีบำบัด','คอร์สเบื้องต้นไม่ใช่ใบประกอบวิชาชีพหรือการรับรองทำงาน','ตรวจหลักสูตรและเกณฑ์รับเข้าของสถาบันที่สนใจ'),
    'thai-mooc':g('รายวิชาออนไลน์ด้านศิลปกรรมท้องถิ่นชายแดนใต้ รวมบริบทดนตรีและการแสดง',['อ่านหัวข้อและระยะเวลา','ตรวจเปิดลงทะเบียน','เลือกตัวอย่างหนึ่งอย่างมาเปรียบเทียบกับดนตรีท้องถิ่นของตน'], 'คนสนใจมรดกดนตรีไทยและบริบทชุมชน','เป็นการเรียนภาพรวม ไม่ใช่คลาสฝึกเล่นเครื่องเฉพาะ','ค้นผู้สอนหรือชุมชนปฏิบัติจริงในพื้นที่'),
    mahidol:g('หน้ารวมประกาศรับสมัครและทางไปยังหลักสูตรดนตรีหลายระดับ',['เลือกระดับที่ต้องการ','อ่านเกณฑ์ audition และเอกสารปีปัจจุบัน','จัดรายการทักษะ/ผลงานที่ต้องเตรียม'], 'ผู้เตรียมเรียนดนตรีในระบบ','วันรับสมัคร ค่าใช้จ่าย และเกณฑ์เปลี่ยนทุกปี','นำเกณฑ์ปัจจุบันไปวางแผนฝึกกับครู'),
    soundbrenner:g('เมโทรนอมบนมือถือที่ปรับ tempo, subdivision และ accent ได้',['ตั้ง 60 BPM แบบ 4/4','ตบมือกับคลิก 1 นาที','ลอง subdivision เป็นเขบ็ตหนึ่งชั้น'], 'คนเริ่มฝึกเวลาและนักดนตรีที่ต้องการเครื่องมือพกพา','บางคุณสมบัติอยู่ในแผนชำระเงิน; ตรวจหน้า App Store','เพิ่ม tempo ทีละน้อยและบันทึกจุดที่เล่นพลาด'),
    tonalenergy:g('tuner และ metronome ที่มีการแสดง pitch และการบันทึกเสียง',['ตั้ง concert pitch/เครื่องดนตรี','เล่นโน้ตยาว 5 วินาที','ฟังการแกว่งของ pitch แล้วปรับลม/นิ้ว'], 'นักร้อง เครื่องลม และเครื่องสายที่ฝึก intonation','เป็นแอปเสียเงิน และผล tuner ต้องใช้ไมโครโฟนในสภาพแวดล้อมที่เหมาะ','ฝึกโน้ตเดียวกับ drone หรือครู'),
    guitartuna:g('tuner ตรวจเสียงสายผ่านไมโครโฟน พร้อมเครื่องมือคอร์ด/แบบฝึกบางส่วน',['อนุญาตไมโครโฟน','เลือกเครื่องและ tuning ให้ถูก','ดีดทีละสายแล้วปรับจนตรง'], 'ผู้เริ่มเครื่องสายที่ต้องตั้งเสียงก่อนซ้อม','แอปมีการขายสมาชิก; การตั้งเสียงในที่เสียงดังคลาดเคลื่อนได้','เมื่อเสียงตรงแล้วฝึกคอร์ดง่ายกับเมโทรนอม'),
    moises:g('แอปแยก stems เสียงร้อง/เครื่องดนตรี และปรับความเร็วหรือคีย์เพื่อซ้อม',['เลือกเพลงที่มีสิทธิใช้งาน','นำเข้าและรอประมวลผล','ปิดเสียงส่วนของตนแล้วเล่นตาม'], 'นักดนตรีที่ต้องการซ้อมกับ backing และแกะพาร์ต','คุณภาพแยก stems ไม่สมบูรณ์ทุกเพลง และบางฟีเจอร์มีค่าใช้จ่าย','อัดตัวเองแล้วเทียบกับต้นฉบับอย่างมีเป้าหมาย'),
    anytune:g('เครื่องเล่นเพลงเพื่อชะลอ tempo, วนท่อน และปรับคีย์',['นำเข้าไฟล์ของตน','เลือกท่อน 4–8 ห้องเป็น loop','ลดความเร็วแล้วค่อยเพิ่มทีละขั้น'], 'ผู้แกะโซโล่หรือท่อนเร็วจากเสียงจริง','ตรวจชนิดไฟล์ที่เข้าถึงได้และสิทธิการใช้เพลง','จดโน้ตหรือแท็บของท่อนที่แกะได้'),
    ireal:g('คลัง chord chart และวงประกอบจำลองที่ปรับคีย์ จังหวะ และ tempo',['เลือกเพลง/คอร์ด progression','ตั้ง tempo ที่เล่นไหว','เล่นคอร์ดรอบแรกและ solo รอบสอง'], 'ผู้ฝึก jazz, improvisation และการอ่านคอร์ด','ไม่ได้ให้ recording ต้นฉบับหรือ melody ของเพลง','อัดการเล่นเพื่อฟัง time feel และการเปลี่ยนคอร์ด'),
    tenuto:g('ชุดแบบฝึกทฤษฎีและ ear training ที่กำหนดช่วงโจทย์ได้',['เลือก note/interval exercise','จำกัดช่วงเสียงตามทักษะ','ฝึก 10 ข้อและเทียบผลวันถัดไป'], 'ผู้เรียนที่ต้องการฝึกสม่ำเสมอแบบออฟไลน์บน iOS','แอปเสียเงิน; บทเรียนและแบบฝึกเว็บของผู้พัฒนามีให้ใช้ฟรี','ขยายช่วงโจทย์เมื่อทำถูกต่อเนื่อง'),
    garageband:g('เครื่องดนตรีสัมผัส Live Loops และ timeline หลายแทร็กสำหรับทำเดโม',['เปิด Live Loops','เลือกชุดเสียงแล้วบันทึก 8 ห้อง','เพิ่มเสียงร้องหรือทำนองหนึ่งแทร็ก'], 'ผู้เริ่มแต่งเพลงที่มี iPhone/iPad','เฉพาะอุปกรณ์ Apple ที่รองรับ; เสียงในแอปมีเงื่อนไขการใช้','ส่งออกเดโมแล้วขอ feedback จากเพื่อน'),
    hookpad:g('พื้นที่วาง chord progression และ melody พร้อมภาพความสัมพันธ์ของทฤษฎี',['เปิดตัวอย่างและคู่มือ','สร้าง progression 4 คอร์ด','ทดลองย้ายโน้ตทำนองแล้วฟังความต่าง'], 'ผู้แต่งเพลงที่อยากเชื่อมทฤษฎีกับเสียง','การแก้ไขบนมือถือไม่เหมาะ; ตรวจแผนการใช้งานและราคา','ส่งไอเดียไปขยายใน DAW'),
    songbook:g('แอปจัด chord/lyrics ของตนเป็นรายการเพลงสำหรับซ้อมและแสดง',['นำเข้าไฟล์ ChordPro ที่ใช้ได้','จัด setlist 3 เพลง','ทดสอบการเลื่อนและการเปลี่ยนเพลง'], 'นักร้อง/วงที่เล่นเพลงด้วย chord chart','แอปเสียเงิน และต้องมีสิทธิใช้เนื้อเพลง/คอร์ดที่นำเข้า','ซ้อม setlist ตามลำดับการแสดงจริง'),
    forscore:g('ตัวอ่าน PDF score พร้อม annotation, setlist, page turn และเครื่องมือฝึก',['นำเข้า PDF ของตน','ทำเครื่องหมาย cue/fingering','จัด setlist และลองพลิกหน้าก่อนขึ้นเวที'], 'นักดนตรีที่ใช้โน้ตระหว่างซ้อมและแสดง','แอปเสียเงิน; อาจมีฟีเจอร์ Pro เพิ่ม และต้องมีสิทธิไฟล์โน้ต','สำรองไฟล์และทดสอบอุปกรณ์ก่อนการแสดง'),
    audacity:g('โปรแกรมอัด/ตัดต่อ waveform บนเดสก์ท็อป',['ดาวน์โหลดจากเว็บทางการ','เลือกไมโครโฟนและอัด 30 วินาที','ตัด silence แล้วส่งออกไฟล์ทดลอง'], 'ผู้ทำ podcast, เดโมเสียง และครูที่จัดไฟล์เสียง','ไม่มีแอปมือถือทางการ; การอัดหลายแทร็กแบบ DAW มีข้อจำกัด','ถ้าจะผลิตเพลงหลายแทร็ก ให้ลอง BandLab หรือ REAPER'),
    reaper:g('DAW เดสก์ท็อปสำหรับอัด จัดแทร็ก ตัดต่อ มิกซ์ และ export',['ดาวน์โหลด trial ทางการ','สร้างโปรเจกต์และอัด 2 แทร็ก','ปรับระดับเสียงแล้ว export WAV'], 'ผู้ต้องการเรียน production workflow อย่างจริงจัง','ทดลอง 60 วัน; หลังจากนั้นต้องซื้อไลเซนส์','ทำโปรเจกต์สั้นให้เสร็จและขอ feedback เรื่อง mix'),
    'ableton-live':g('DAW ที่มี Session View สำหรับทดลองไอเดียและ Arrangement View สำหรับเรียบเรียง',['ดูภาพรวมเครื่องมือและสเปก','ลอง trial ทางการ','ทำ loop 8 ห้องแล้วจัดเป็น intro/verse'], 'ผู้สนใจ electronic production และ live performance','trial มีวันหมดอายุ; รุ่นและสเปกต่างกัน','ใช้บท Learning Music ปูพื้นแล้วทำเดโมจริง'),
    'dorico-se':g('โปรแกรม notation รุ่นเริ่มต้นสำหรับเขียน score และจัดหน้า',['ติดตั้งรุ่น SE','สร้าง score เครื่องเดียว 8 ห้อง','ทดลองใส่ dynamics และ export PDF'], 'นักเรียน composition/arranging ที่ต้องการ notation ฟรี','รุ่น SE จำกัดจำนวนผู้เล่นและบางฟีเจอร์','นำ score ให้ผู้เล่นอ่านแล้วแก้จุดที่สื่อสารไม่ชัด'),
    'logic-ipad':g('DAW สำหรับ iPad ที่มีการอัด MIDI/audio, virtual instruments และเครื่องมือมิกซ์',['ตรวจ iPad รุ่นที่รองรับ','ดูแผนสมาชิกและ trial ปัจจุบัน','ทำโปรเจกต์ 4 แทร็กสั้นก่อนย้ายงานจริง'], 'ผู้ผลิตเพลงที่มี iPad และต้องการ workflow ระดับสูง','ราคาและสิทธิเต็มรูปแบบตามแผน; ตรวจเงื่อนไขใน App Store','ส่งออกเสียงทดลองแล้วเทียบกับ GarageBand'),
    qlab:g('workspace เรียง audio/video/lighting cues ตามลำดับโชว์',['ติดตั้งบน Mac','เพิ่มเสียง cue 2 รายการ','ลอง Go, stop และ fade ในการซ้อมจำลอง'], 'sound designer, stage manager และผู้จัดการแสดง','ฟังก์ชันระดับสูงมีค่าไลเซนส์; ตรวจเครื่องและ output ก่อนโชว์','ทำ cue sheet กับทีมและซ้อม run-through'),
    soundslice:g('player ที่ผูก notation/tab กับเสียงหรือวิดีโอและมี loop/slowdown',['เปิดตัวอย่างที่ใช้ได้','เลือก 2 ห้องเป็น loop','ลดความเร็วแล้วเล่นตามจนตรง'], 'ผู้เรียนที่อ่านโน้ต/แท็บพร้อมฟังเสียงจริง','การนำเข้า/แชร์และฟีเจอร์บางส่วนขึ้นกับแผนและสิทธิเนื้อหา','เพิ่ม tempo แล้วบันทึกจุดที่ยังพลาด'),
    flat:g('ตัวเขียนโน้ตบน browser ที่เล่นกลับ แชร์ และร่วมแก้ไขได้',['สมัครบัญชี','สร้าง score 4 ห้อง','แชร์ให้ครูอ่านและคอมเมนต์'], 'นักเรียน/ครูที่ทำโน้ตร่วมกันโดยไม่ติดตั้งโปรแกรม','แผนฟรีจำกัดบางฟังก์ชันและการส่งออก','นำ feedback มาปรับ score รุ่นถัดไป'),
    'pro-tools':g('DAW สำหรับ recording, editing, comping, mixing และงานเสียงที่ต้องส่ง session ระหว่างทีม',['ดูแผน Intro และสเปก','สร้าง session สั้น อัดเสียง 2 take','ทดลอง comp และ export stem'], 'ผู้เรียนสาย recording/mixing และผู้เตรียมทำงานร่วมสตูดิโอ','รุ่นฟรีมีขีดจำกัด; แผน Studio/Ultimate และปลั๊กอินมีค่าใช้จ่าย','ฝึกจัดชื่อแทร็กและส่งไฟล์ให้ผู้ร่วมงานเปิดได้'),
    'logic-mac':g('DAW บน Mac สำหรับ songwriting, beat making, MIDI, recording และ mixing',['ตรวจ Mac ที่รองรับ','สร้างเพลง 8 ห้องจาก software instrument','เพิ่มเสียงร้องแล้ว bounce demo'], 'นักแต่งเพลง/โปรดิวเซอร์ที่ใช้ Mac','ซื้อแอปและต้องมี Mac ที่รองรับ; ราคา App Store อาจเปลี่ยน','เทียบผลกับ GarageBand ก่อนย้ายงานจริง'),
    'dorico-pro':g('โปรแกรม notation/engraving สำหรับ score และ part ที่ต้องอ่านและพิมพ์ในงานจริง',['ทดลองงานเดียวกันใน Dorico SE','เปิด trial Pro หากต้องทำวงใหญ่','สร้าง score แล้วส่ง part ให้นักดนตรีทดลองอ่าน'], 'ผู้เรียบเรียง นักประพันธ์ และ copyist','รุ่น Pro เสียเงิน; การย้ายงานจากซอฟต์แวร์อื่นควรตรวจ MusicXML','แก้ score ตาม feedback ของผู้เล่นและผู้จัดพิมพ์'),
    sibelius:g('โปรแกรม notation สำหรับสร้าง score, part และงานส่งต่อให้ทีมที่ใช้ Sibelius',['ดูรุ่น Artist/Ultimate','สร้าง score วงเล็ก','ส่ง MusicXML/PDF หรือไฟล์ native ตามที่ทีมขอ'], 'ผู้จัดทำโน้ตและทีมที่ต้องเข้ากันได้กับไฟล์ Sibelius','ราคาและฟีเจอร์แตกต่างตามแผน; ต้องตกลงเวอร์ชันไฟล์','ทดสอบเปิดไฟล์กับผู้ร่วมงานก่อนส่งงานจริง'),
    mainstage:g('โปรแกรมสร้าง concert/patch บน Mac สำหรับคีย์บอร์ด กีตาร์ เสียงร้อง และ MIDI controller',['ต่อ controller/audio interface','สร้าง 2 patches และกำหนดปุ่มสลับ','ซ้อมเปลี่ยน patch โดยไม่หยุดเสียง'], 'นักดนตรีที่เล่นเสียง virtual instruments/เอฟเฟกต์สด','ต้องมี Mac และ rig ที่เสถียร; ทดสอบ latency และไฟสำรอง','ทำ setlist กับ patch map แล้วซ้อมตามโชว์จริง')
  };
  for(const r of resources)r.guide=guides[r.id];
  const sourceOverrides={audacity:'https://www.audacityteam.org/faq/',reaper:'https://www.reaper.fm/purchase.php',hookpad:'https://www.hooktheory.com/hookpad/pricing',qlab:'https://qlab.app/shop/',soundslice:'https://www.soundslice.com/help/en/player/basic/99/overview/',flat:'https://help.flat.io/en/general/what-is-flat/'};
  for(const r of resources){
    if(sourceOverrides[r.id])r.source=sourceOverrides[r.id];
    r.sourceType=r.url.includes('apps.apple.com')?'Apple App Store — ข้อมูลจากผู้พัฒนา':'เว็บไซต์ผู้พัฒนา/สถาบัน';
  }
  Object.assign(resources.find(r=>r.id==='hookpad'),{cost:'freemium',costText:'เริ่มแต่งคอร์ด/ทำนองฟรี; ฟีเจอร์เพิ่มมีค่าใช้จ่าย',account:'สมัครเพื่อบันทึกบนคลาวด์'});
  resources.find(r=>r.id==='soundbrenner').alternates=[{name:'Google Play (Android)',url:'https://play.google.com/store/apps/details?id=com.soundbrenner.pulse'}];
  resources.find(r=>r.id==='guitartuna').alternates=[{name:'Google Play (Android)',url:'https://play.google.com/store/apps/details?id=com.ovelin.guitartuna'}];
  resources.find(r=>r.id==='moises').alternates=[{name:'Google Play (Android)',url:'https://play.google.com/store/apps/details?id=ai.moises'}];
  const categories=[['all','ทั้งหมด'],['try','ทดลองก่อน'],['theory','ทฤษฎี/โสต'],['songwriting','แต่งเพลง'],['metronome','เมโทรนอม'],['tuner','ตั้งเสียง'],['practice','ซ้อม/แกะเพลง'],['notation','เขียนโน้ต'],['recording','อัด/มิกซ์'],['performance','ขึ้นเวที'],['teacher','หาครู'],['culture','วัฒนธรรม'],['pathway','เรียนต่อ/อาชีพ']];
  function selectResources(filters={}){const query=String(filters.query||'').trim().toLocaleLowerCase();return resources.filter(r=>(!filters.category||filters.category==='all'||r.category===filters.category)&&(!filters.freeOnly||['free','freemium'].includes(r.cost))&&(!filters.noInstrument||r.noInstrument)&&(!filters.thaiOnly||r.thai)&&(!query||[r.name,r.owner,r.goal,r.category,r.guide.what].join(' ').toLocaleLowerCase().includes(query)))}
  return {resources,categories,selectResources,checked};
});
