(function(){
  'use strict';
  const C=window.MILCore, app=document.getElementById('app');
  const KEY='music-industry-lap-demo-v1';
  function read(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return {}}}
  const saved=read();
  const state={route:'home',role:saved.role||'producer',mission:{step:0,answers:[]},completed:saved.completed||{},weeks:saved.weeks||{},savedOpps:saved.savedOpps||[],filters:{role:'any',mode:'any',budget:'3000',needLoan:false},reflection:saved.reflection||''};
  function persist(){try{localStorage.setItem(KEY,JSON.stringify({role:state.role,completed:state.completed,weeks:state.weeks,savedOpps:state.savedOpps,reflection:state.reflection}))}catch{}}
  function esc(v){return String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]))}
  function baht(v){return Number(v).toLocaleString('th-TH')+' บาท'}
  function role(id){return C.roles.find(r=>r.id===id)||C.roles[0]}
  function head(kicker,title,subtitle=''){return `<div class="screen-head"><div><div class="section-label">${kicker}</div><h2>${title}</h2>${subtitle?`<p class="subtle">${subtitle}</p>`:''}</div></div>`}
  function home(){const done=Object.keys(state.completed).length,checked=Object.values(state.weeks).filter(Boolean).length;return `<div class="screen"><p class="section-label">YOUR MUSIC JOURNEY</p><div class="hero-card"><div><span class="pill" style="background:#ffffff24;color:#fff">ทางดนตรีของคุณ เริ่มได้วันนี้</span><h2>${done?'วันนี้ลองทำอะไรต่อดี?':'ดนตรีมีมากกว่าหนึ่งทาง'}</h2><p>${done?`คุณลองแล้ว ${done} บทบาท ลองอีกทางหรือดูเส้นทางที่สนใจ`:'ลองทำงานของคนในวงการ ก่อนเลือกว่าจะเรียนอะไร ที่ไหน กับใคร'}</p></div><button type="button" class="button" data-nav="explore">ยังไม่แน่ใจ · สำรวจบทบาท ↗</button></div><button type="button" class="button secondary full" data-nav="people">รู้แล้วว่าจะเรียนอะไร · หาคนสอน</button><div class="section-top"><h3>เริ่มได้ใน 15 นาที</h3><button type="button" class="text-button" data-nav="explore">ดูทุกบทบาท →</button></div>${C.roles.slice(0,3).map(r=>roleCard(r)).join('')}<div class="card lilac"><div class="card-top"><h3>ทางของฉัน</h3><span class="pill lilac">${checked}/8 สัปดาห์</span></div><p class="subtle">ความก้าวหน้าคิดจากสิ่งที่คุณทำและเช็กเอง ไม่มีตัวเลขจำลอง</p><button type="button" class="button outline full" data-nav="path">เปิดแผนฝึก</button></div><p class="hint">ภารกิจใช้ฟรีและทำได้โดยไม่ซื้อเครื่องดนตรี · ครูหรือกิจกรรมภายนอกอาจมีค่าใช้จ่าย</p></div>`}
  function roleCard(r){const done=state.completed[r.id];return `<button type="button" class="role-card" data-role="${r.id}"><span class="role-icon" aria-hidden="true">${r.icon}</span><span><b>${r.name}</b><small>${r.blurb}</small></span><span class="arrow" aria-hidden="true">${done?'✓':'›'}</span></button>`}
  function explore(){return `<div class="screen">${head('EXPLORE','ใครทำอะไรในดนตรี?','ลองบทบาทได้โดยไม่ต้องรู้ชื่อสาขาหรือมีเครื่องก่อน')}<div class="pill-row"><span class="pill">แสดง</span><span class="pill peach">สร้าง</span><span class="pill lilac">เบื้องหลัง</span><span class="pill">สอน</span></div><div class="section-top"><h3>บทบาทที่ลองได้ตอนนี้</h3><span class="subtle">3 ภารกิจ</span></div>${C.roles.slice(0,3).map(roleCard).join('')}<div class="section-top"><h3>สำรวจสายอื่น</h3><span class="subtle">ดูทักษะและทางเรียน</span></div>${C.roles.slice(3).map(roleCard).join('')}<div class="card soft"><h3>ไม่รู้จะเลือกอะไร?</h3><p class="subtle">เริ่มที่บทบาทที่ดูสนุก ไม่ต้องผูกมัดว่าจะเรียนสายนั้นตลอด</p><button type="button" class="button secondary full" data-role="producer">สุ่มลองงานสร้างเพลง</button></div></div>`}
  function rolePage(){const r=role(state.role),has=!!C.missions[r.id];return `<div class="screen">${head(r.group,r.name,r.blurb)}<div class="card soft"><span class="role-icon" aria-hidden="true">${r.icon}</span><div class="divider"></div><h3>สายนี้เรียนรู้อะไร</h3><p>${r.learn}</p><div class="pill-row">${r.skills.map(s=>`<span class="pill">${s}</span>`).join('')}</div></div><div class="card peach"><h3>งานที่ผู้เรียนจะได้ลอง</h3><p>${has?C.missions[r.id].brief:'บทบาทนี้ยังอยู่ในแผนสร้างภารกิจฉบับเต็ม คุณดูทักษะและค้นหาคนสอนได้ก่อน'}</p><p class="subtle">${has?'ใช้เวลา 15 นาที · มือถือหรือกระดาษ':'ยังไม่มี simulation ที่เปิดใน demo'}</p></div>${has?'<button type="button" class="button full" data-start="'+r.id+'">เริ่มภารกิจนี้ →</button>':''}<button type="button" class="button outline full" data-nav="people">ดูคนสอนและทางเรียน</button><button type="button" class="text-button" data-nav="explore">← ดูสายอื่น</button></div>`}
  function mission(){const m=C.missions[state.role];if(!m)return rolePage();const i=state.mission.step,q=m.questions[i],selected=state.mission.answers[i];return `<div class="screen">${head('TRY THE ROLE',m.title,m.brief)}<div class="card"><div class="card-top"><span class="pill">${m.time} นาที</span><span class="step-label">ตัดสินใจ ${i+1} / ${m.questions.length}</span></div><div class="progress-track"><span style="width:${((i+1)/m.questions.length)*100}%"></span></div><h3>${q.text}</h3>${q.options.map((o,n)=>`<button type="button" class="option ${selected===n?'selected':''}" data-answer="${n}" aria-pressed="${selected===n}">${o.text}</button>`).join('')}${selected!==undefined?`<div class="feedback ${q.options[selected].points===0?'warn':''}">${q.options[selected].feedback}</div>`:''}</div><button type="button" class="button full" data-next ${selected===undefined?'disabled':''}>${i===m.questions.length-1?'ดูผลการตัดสินใจ':'ข้อต่อไป'} →</button>${i>0?'<button type="button" class="button outline full" data-prev>← กลับไปแก้ข้อก่อน</button>':''}<p class="hint">นี่คือสถานการณ์ตัดสินใจของงานจริงฉบับย่อ ไม่ใช่การทดสอบความถนัดหรือการฝึกเทคนิคเครื่องดนตรีเต็มรูปแบบ</p></div>`}
  function result(){const m=C.missions[state.role],score=C.missionScore(state.role,state.mission.answers),date=new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'short',year:'numeric'}).format(new Date());return `<div class="screen">${head('REFLECT','คุณลองงานนี้แล้ว','ผลนี้เป็นการสะท้อนการตัดสินใจ ไม่ใช่คำตัดสินความสามารถ')}<div class="card"><div class="card-top"><h3>${m.title}</h3><span class="pill">${score}/4 จุดเรียนรู้</span></div><p class="subtle">ตัวอย่างชิ้นงานที่ควรทำต่อ</p><p>${m.artifact}</p><p class="subtle">บันทึกในเครื่องเมื่อ ${date}</p></div><div class="card soft"><h3>สิ่งที่ตัดสินใจในโจทย์</h3>${m.questions.map((q,i)=>`<p class="small"><b>${i+1}. ${q.options[state.mission.answers[i]].text}</b><br>${q.options[state.mission.answers[i]].feedback}</p>`).join('')}</div><label class="field" for="reflection">ช่วงไหนที่คุณอยากทำอีก?</label><textarea id="reflection" class="field-control" rows="3" placeholder="บันทึกความคิดไว้ในเครื่องนี้">${esc(state.reflection)}</textarea><button type="button" class="button full" data-save-reflection>บันทึกและดูทางเรียนต่อ</button><button type="button" class="button outline full" data-nav="explore">ลองบทบาทอื่น</button></div>`}
  function people(){const f=state.filters,ranked=C.matchProviders({role:f.role==='any'?'':f.role,mode:f.mode,budget:f.budget,needLoan:f.needLoan});return `<div class="screen">${head('MATCH','คนสอนและที่เรียน','เปรียบเทียบตามสิ่งที่คุณต้องการ ไม่ใช้ชื่อเสียงอย่างเดียว')}<div class="card"><div class="card-top"><h3>เงื่อนไขของคุณ</h3><span class="pill demo">ข้อมูลสมมติ</span></div><label class="field" for="filter-role">สายที่สนใจ</label><select class="field-control" id="filter-role" data-filter="role"><option value="any" ${f.role==='any'?'selected':''}>ทุกสาย</option>${C.roles.slice(0,3).map(r=>`<option value="${r.id}" ${f.role===r.id?'selected':''}>${r.name}</option>`).join('')}</select><label class="field" for="filter-budget">งบเดือนแรกสูงสุด (4 ครั้ง + ค่าเพิ่ม/เดินทาง)</label><select class="field-control" id="filter-budget" data-filter="budget">${[1500,2500,3000,5000,10000].map(n=>`<option value="${n}" ${f.budget===String(n)?'selected':''}>${baht(n)}</option>`).join('')}</select><label class="field">รูปแบบเรียน</label><div class="chip-row">${[['any','ทั้งหมด'],['onsite','พบตัว'],['online','ออนไลน์']].map(([v,l])=>`<button type="button" class="chip ${f.mode===v?'selected':''}" data-mode="${v}">${l}</button>`).join('')}</div><label class="week-row"><input type="checkbox" data-loan ${f.needLoan?'checked':''}><span><b>ต้องมีเครื่องให้ลอง/ยืม</b>ช่วยเริ่มโดยไม่ต้องซื้อทันที</span></label></div><div class="section-top"><h3>ทางเลือกที่เทียบได้</h3><span class="subtle">${ranked.length} รายการตัวอย่าง</span></div>${ranked.length?``:`<div class="empty">ยังไม่มีทางเลือกตัวอย่างที่ตรงเงื่อนไข ลองเปลี่ยนสาย รูปแบบเรียน หรือการยืมเครื่อง</div>`}${ranked.map(p=>`<div class="card"><div class="card-top"><span class="pill">${p.kind}</span><span class="pill demo">ยังไม่ตรวจจริง</span></div><div class="compare"><div><h3>${p.name}</h3><p class="subtle">${p.mode==='online'?'ออนไลน์':'พบตัว · '+p.area} · ${p.level}</p></div><div class="price">${baht(p.total)}</div></div><p class="subtle">งบเดือนแรกตัวอย่าง: 4 × ${baht(p.price)} + ค่าเพิ่ม ${baht(p.extras)} + เดินทาง ${baht(p.travel*4)}</p><p class="small">${p.method}</p><div class="pill-row">${p.reasons.map(x=>`<span class="pill">${x}</span>`).join('')}${p.overBudget?'<span class="pill peach">เกินงบที่เลือก</span>':''}${p.loan?'<span class="pill">มีเครื่องให้ลอง</span>':''}</div><div class="source-note">ข้อมูลและราคาแต่งขึ้นเพื่อสาธิตสูตรและการเปรียบเทียบ · ไม่มีการจอง</div></div>`).join('')}<p class="hint">เมื่อใช้ข้อมูลจริง ต้องตรวจวันอัปเดต ราคา เงื่อนไข และความพร้อมกับผู้ให้บริการก่อนแสดงผล</p></div>`}
  function path(){const done=Object.values(state.weeks).filter(Boolean).length,missions=Object.keys(state.completed);return `<div class="screen">${head('MY PATH','ทางของฉัน','แผนนี้แก้ได้ เปลี่ยนสายได้ และหยุดพักได้')}<div class="card"><div class="card-top"><h3>แผนทดลอง 8 สัปดาห์</h3><span class="pill">${done}/8 เสร็จแล้ว</span></div><div class="progress-track"><span style="width:${done/8*100}%"></span></div><p class="subtle">ความคืบหน้าคิดจากรายการที่คุณทำเครื่องหมายเอง</p>${C.weeks.map(([n,title,detail])=>`<div class="week-row"><input type="checkbox" id="week-${n}" data-week="${n}" ${state.weeks[n]?'checked':''}><label for="week-${n}"><b>สัปดาห์ ${n} · ${title}</b>${detail}</label></div>`).join('')}</div><div class="card soft"><h3>งานที่คุณทดลอง</h3>${missions.length?missions.map(id=>`<p class="small">✓ ${role(id).name} · ${state.completed[id].score}/4 จุดเรียนรู้</p>`).join(''):'<p class="subtle">ยังไม่มีงานที่ทำเสร็จ ลองเริ่มบทบาทแรกได้เลย</p>'}<button type="button" class="button secondary full" data-nav="explore">สำรวจงานอื่น</button></div>${state.reflection?`<div class="card peach"><h3>บันทึกของฉัน</h3><p>${esc(state.reflection)}</p></div>`:''}<div class="section-top"><h3>คนและโอกาส</h3><button type="button" class="text-button" data-nav="opportunities">ดูทั้งหมด →</button></div>${state.savedOpps.length?state.savedOpps.map(id=>{const o=C.opportunities.find(x=>x.id===id);return o?`<div class="card"><h3>${o.title}</h3><p class="subtle">${o.type} · ${o.place}</p></div>`:''}).join(''):'<div class="empty">ยังไม่ได้บันทึกโอกาส ลองดูวงหรือกิจกรรมตัวอย่าง</div>'}<button type="button" class="button outline full" data-nav="opportunities">ดูโอกาสในชุมชน</button></div>`}
  function opportunities(){return `<div class="screen">${head('BELONG','พบคนและโอกาส','ข้อมูลทั้งหมดในหน้านี้เป็นโจทย์ตัวอย่าง ไม่ใช่งานที่เปิดรับจริง')}<div class="card lilac"><h3>ชุมชนเพื่อทำงานร่วมกัน</h3><p>เริ่มจากกลุ่มเล็กที่มีผู้ดูแลและกติกาให้ feedback อย่างเคารพกัน</p></div>${C.opportunities.map(o=>`<div class="card"><div class="opportunity"><div><span class="pill lilac">${o.type}</span><h3 style="margin-top:8px">${o.title}</h3></div><span class="pill">${o.cost}</span></div><p class="subtle">${o.place} · ${o.detail}</p><button type="button" class="button ${state.savedOpps.includes(o.id)?'secondary':'outline'} full" data-save-opp="${o.id}">${state.savedOpps.includes(o.id)?'บันทึกแล้ว ✓':'บันทึกไว้ในทางของฉัน'}</button></div>`).join('')}<p class="hint">รุ่นใช้งานจริงต้องมีวัน สถานที่ ผู้จัด เงื่อนไข สิทธิ และวิธีติดต่อที่ตรวจสอบได้ก่อนเผยแพร่</p></div>`}
  const routes={home,explore,role:rolePage,mission,result,people,path,opportunities};
  function render(scroll=true){app.innerHTML=routes[state.route]();document.querySelectorAll('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.nav===state.route||(state.route==='role'&&b.dataset.nav==='explore')||(state.route==='result'&&b.dataset.nav==='mission')||(state.route==='opportunities'&&b.dataset.nav==='path')));if(scroll)app.scrollTop=0}
  function navigate(target){state.route=target==='mission'&&!C.missions[state.role]?'explore':target;if(target==='mission')state.mission={step:0,answers:[]};render()}
  document.addEventListener('click',event=>{const el=event.target.closest('button');if(!el)return;
    if(el.dataset.nav){navigate(el.dataset.nav);return}
    if(el.dataset.role){state.role=el.dataset.role;persist();state.route='role';render();return}
    if(el.dataset.start){state.role=el.dataset.start;state.mission={step:0,answers:[]};state.route='mission';persist();render();return}
    if(el.dataset.answer!==undefined){state.mission.answers[state.mission.step]=Number(el.dataset.answer);render(false);return}
    if(el.hasAttribute('data-prev')){state.mission.step=Math.max(0,state.mission.step-1);render();return}
    if(el.hasAttribute('data-next')){const m=C.missions[state.role];if(state.mission.answers[state.mission.step]===undefined)return;if(state.mission.step<m.questions.length-1){state.mission.step++;render()}else{state.completed[state.role]={score:C.missionScore(state.role,state.mission.answers),date:new Date().toISOString()};persist();state.route='result';render()}return}
    if(el.hasAttribute('data-save-reflection')){state.reflection=document.getElementById('reflection')?.value.trim().slice(0,500)||'';persist();state.filters.role=state.role;state.route='people';render();return}
    if(el.dataset.mode){state.filters.mode=el.dataset.mode;render(false);return}
    if(el.dataset.saveOpp){const id=el.dataset.saveOpp;state.savedOpps=state.savedOpps.includes(id)?state.savedOpps.filter(x=>x!==id):[...state.savedOpps,id];persist();render(false);return}
  });
  document.addEventListener('change',event=>{const el=event.target;if(el.dataset.filter){state.filters[el.dataset.filter]=el.value;render(false)}else if(el.hasAttribute('data-loan')){state.filters.needLoan=el.checked;render(false)}else if(el.dataset.week){state.weeks[el.dataset.week]=el.checked;persist();render(false)}});
  render();
})();
